
animal = Animal.create(name: 'Cow')
primal_cut = PrimalCut.create(name: 'Chuck', animal_id: animal.id)
primal_cut = PrimalCut.create(name: 'Short loin', animal_id: animal.id)
primal_cut = PrimalCut.create(name: 'Rib', animal_id: animal.id)
cut = Cut.create(name: 'Prime Rib', primal_cut_id: primal_cut.id)
cut = Cut.create(name: 'Ribeye', primal_cut_id: primal_cut.id)
cut = Cut.create(name: 'Porterhouse', animal_id: animal.id)
cut = Cut.create(name: 'T-bone', animal_id: animal.id)
cut = Cut.create(name: 'Strip', animal_id: animal.id)

animal = Animal.create(name: 'Pig')
primal_cut = PrimalCut.create(name: 'Jowl', animal_id: animal.id)
primal_cut = PrimalCut.create(name: 'Ham', animal_id: animal.id)
primal_cut = PrimalCut.create(name: 'Loin', animal_id: animal.id)
cut = Cut.create(name: 'Loin Chop', primal_cut_id: primal_cut.id)
cut = Cut.create(name: 'Blade Roast', primal_cut_id: primal_cut.id)
cut = Cut.create(name: 'Babyback Ribs', animal_id: animal.id)
cut = Cut.create(name: 'Spareribs', animal_id: animal.id)
cut = Cut.create(name: 'Hock', animal_id: animal.id)
